name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: ['8', '11']
        exclude:
          - os: windows-latest
            java: '11'
        include:
          - os: ubuntu-latest
            script: ./mvnw
          - os: windows-latest
            script: .\mvnw.cmd
          - os: ubuntu-latest
            java: '11'
            sonar: true
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
    env:
      MAVEN_CMD: ${{ matrix.script }} --batch-mode --show-version --errors --no-transfer-progress --update-snapshots
    steps:
      - name: Determine Checkout Depth
        uses: haya14busa/action-cond@v1.0.2
        id: fetchDepth
        with:
          cond: ${{ matrix.sonar == true }}
          if_true: '0'
          if_false: '1'
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: ${{ steps.fetchDepth.outputs.value }}
      - name: Set up Java
        uses: actions/setup-java@v2.1.0
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: Cache Maven Packages
        uses: actions/cache@v2.1.5
        with:
          key: ${{ matrix.os }}-java${{ matrix.java }}-m2-${{ hashFiles('.mvn/wrapper/maven-wrapper.properties', 'pom.xml') }}
          path: |
            ~/.m2/repository
            ~/.m2/wrapper/dists
      - name: Build
        run: ${{ env.MAVEN_CMD }} -Penable-jacoco clean install
      - name: Check Test Report
        uses: scacap/action-surefire-report@v1.10.0
        with:
          fail_on_test_failures: true
          skip_publishing: true
      - name: Cache SonarCloud Packages
        if: ${{ matrix.sonar }}
        uses: actions/cache@v2.1.5
        with:
          key: ${{ matrix.os }}-java${{ matrix.java }}-sonar
          path: ~/.sonar/cache
      - name: Execute SonarScanner
        if: ${{ matrix.sonar }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ env.MAVEN_CMD }} sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
